/*
 * This file is generated by jOOQ.
 */
package com.suixingpay.jooq.entity.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLog implements Serializable {

    private static final long serialVersionUID = -621789772;

    private Integer   id;
    private String    ipAddress;
    private Integer   operId;
    private String    userName;
    private String    moduleName;
    private String    methodName;
    private String    methodDesc;
    private String    operContent;
    private Timestamp createTime;
    private Integer   appId;

    public SysLog() {}

    public SysLog(SysLog value) {
        this.id = value.id;
        this.ipAddress = value.ipAddress;
        this.operId = value.operId;
        this.userName = value.userName;
        this.moduleName = value.moduleName;
        this.methodName = value.methodName;
        this.methodDesc = value.methodDesc;
        this.operContent = value.operContent;
        this.createTime = value.createTime;
        this.appId = value.appId;
    }

    public SysLog(
        Integer   id,
        String    ipAddress,
        Integer   operId,
        String    userName,
        String    moduleName,
        String    methodName,
        String    methodDesc,
        String    operContent,
        Timestamp createTime,
        Integer   appId
    ) {
        this.id = id;
        this.ipAddress = ipAddress;
        this.operId = operId;
        this.userName = userName;
        this.moduleName = moduleName;
        this.methodName = methodName;
        this.methodDesc = methodDesc;
        this.operContent = operContent;
        this.createTime = createTime;
        this.appId = appId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public Integer getOperId() {
        return this.operId;
    }

    public void setOperId(Integer operId) {
        this.operId = operId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getModuleName() {
        return this.moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    public String getMethodName() {
        return this.methodName;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public String getMethodDesc() {
        return this.methodDesc;
    }

    public void setMethodDesc(String methodDesc) {
        this.methodDesc = methodDesc;
    }

    public String getOperContent() {
        return this.operContent;
    }

    public void setOperContent(String operContent) {
        this.operContent = operContent;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Integer getAppId() {
        return this.appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysLog (");

        sb.append(id);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(operId);
        sb.append(", ").append(userName);
        sb.append(", ").append(moduleName);
        sb.append(", ").append(methodName);
        sb.append(", ").append(methodDesc);
        sb.append(", ").append(operContent);
        sb.append(", ").append(createTime);
        sb.append(", ").append(appId);

        sb.append(")");
        return sb.toString();
    }
}
