/*
 * This file is generated by jOOQ.
 */
package com.suixingpay.jooq.entity.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUser implements Serializable {

    private static final long serialVersionUID = 578145360;

    private Integer   id;
    private String    userName;
    private String    realName;
    private String    email;
    private String    phone;
    private String    pswd;
    private Timestamp createTime;
    private Timestamp lastLoginTime;
    private Integer   userStatus;

    public SysUser() {}

    public SysUser(SysUser value) {
        this.id = value.id;
        this.userName = value.userName;
        this.realName = value.realName;
        this.email = value.email;
        this.phone = value.phone;
        this.pswd = value.pswd;
        this.createTime = value.createTime;
        this.lastLoginTime = value.lastLoginTime;
        this.userStatus = value.userStatus;
    }

    public SysUser(
        Integer   id,
        String    userName,
        String    realName,
        String    email,
        String    phone,
        String    pswd,
        Timestamp createTime,
        Timestamp lastLoginTime,
        Integer   userStatus
    ) {
        this.id = id;
        this.userName = userName;
        this.realName = realName;
        this.email = email;
        this.phone = phone;
        this.pswd = pswd;
        this.createTime = createTime;
        this.lastLoginTime = lastLoginTime;
        this.userStatus = userStatus;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPswd() {
        return this.pswd;
    }

    public void setPswd(String pswd) {
        this.pswd = pswd;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getLastLoginTime() {
        return this.lastLoginTime;
    }

    public void setLastLoginTime(Timestamp lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public Integer getUserStatus() {
        return this.userStatus;
    }

    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUser (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(realName);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(pswd);
        sb.append(", ").append(createTime);
        sb.append(", ").append(lastLoginTime);
        sb.append(", ").append(userStatus);

        sb.append(")");
        return sb.toString();
    }
}
