/*
 * This file is generated by jOOQ.
 */
package com.suixingpay.jooq.entity;


import com.suixingpay.jooq.entity.tables.FlywaySchemaHistory;
import com.suixingpay.jooq.entity.tables.SysLog;
import com.suixingpay.jooq.entity.tables.SysUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTest extends SchemaImpl {

    private static final long serialVersionUID = -1195033215;

    /**
     * The reference instance of <code>jooq_test</code>
     */
    public static final JooqTest JOOQ_TEST = new JooqTest();

    /**
     * The table <code>jooq_test.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.suixingpay.jooq.entity.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jooq_test.sys_log</code>.
     */
    public final SysLog SYS_LOG = com.suixingpay.jooq.entity.tables.SysLog.SYS_LOG;

    /**
     * The table <code>jooq_test.sys_user</code>.
     */
    public final SysUser SYS_USER = com.suixingpay.jooq.entity.tables.SysUser.SYS_USER;

    /**
     * No further instances allowed
     */
    private JooqTest() {
        super("jooq_test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            SysLog.SYS_LOG,
            SysUser.SYS_USER);
    }
}
