spring:
  profiles:
    active: dev
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/jooq_test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 111
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql
  flyway:
    clean-disabled: true #禁用clean操作
    enabled: true #使flyway生效
    baseline-on-migrate: true #初始化时如果不存在迁移记录表，默认新建一个
    out-of-order: true #防止开发环境下漏掉没来得及apply的文件，产品环境最好设为false
    locations: classpath:/db/migration
